### ISSUE TITLE
About the trace dataset

### ISSUE THREAD

**Issue by chengquan98** [transys-project/afr#1]
hi,
I couldn't find  the data folder (the online traces and evaluation outputs)  in your repo,  will you upload it in future?

**Comment by mengzili** [comment]
Hi secretu,

Unfortunately our collaborators from Tencent stop us from releasing the original traces. We're now trying to release the traces in a privacy-preserving way (e.g., [DoppelGanger](https://github.com/fjxmlzn/DoppelGANger) ). We're now testing over it. 

If you have some good suggestions to release the traces in a privacy preserving way (not simply anonymize it), please also let us know. Thanks!

**Comment by TheOne-king** [comment]
Hi,
What type should the data be? A video or some frames, like images?

**Comment by mengzili** [comment]
Due to the unexpected obstacles in requesting approval from Tencent, we decide to release sample traces first for users to use the framework first. 

The sample trace uploaded with commit bbeb7bac521c5ab164ab7aedfe2e4e4cb26fa199

Now the code should be directly runnable with the `test-*` setting.

Thanks again for your patience and welcome to more suggestions!
